# This yaml file should create a working version of the service locally via:
# ./gradlew bootRun --args='--spring.profiles.active=local'
fileEventGenerator:
  s3:
    credentials:
      provider: PROFILE
      profile: guardian
    region: us-gov-west-1
    oneObject:
      bucket: tdp-raw
      name: raw_cifp/2024/06/13.zip
boogieService:
  boogie:
    enabled: true
logging:
  level: 
    root: info
    org:
      mitre:
        tdp:
          boogie: debug