name: Test
on: [ push ]
jobs:
  unit-test:
    name: Unit Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test -PghprToken=${{github.token}}